package com.mobilisepakistan.pdma.global;

import java.util.ArrayList;

public class evacCenters {



    public static ArrayList<String> getdistrict() {
          ArrayList<String> listHeadrs=new  ArrayList<String>();
        listHeadrs  .add("Mansehra");
        listHeadrs  .add("Mansehra");
        listHeadrs  .add("Mansehra");
        listHeadrs  .add("Mansehra");
        listHeadrs  .add("Mansehra");
        listHeadrs  .add("Mansehra");
        listHeadrs  .add("Battagram");
        listHeadrs  .add("Battagram");
        listHeadrs  .add("Battagram");
        listHeadrs  .add("Torghar");
        listHeadrs  .add("Kohistan Lower");
        listHeadrs  .add("Kohistan Lower");
        listHeadrs  .add("Kohistan Lower");
        listHeadrs  .add("Kohistan Lower");
        listHeadrs  .add("Kohistan Upper");
        listHeadrs  .add("Kohistan Upper");
        listHeadrs  .add("Kohistan Upper");
        listHeadrs  .add("Kolai Palas");
        listHeadrs  .add("Kolai Palas");
        listHeadrs  .add("Kolai Palas");
        listHeadrs  .add("Charsadda");
        listHeadrs  .add("Charsadda");
        listHeadrs  .add("Charsadda");
        listHeadrs  .add("Nowshera");
        listHeadrs  .add("Nowshera");
        listHeadrs  .add("Nowshera");
        listHeadrs  .add("Nowshera");
        listHeadrs  .add("Dir Lower");
        listHeadrs  .add("Dir Lower");
        listHeadrs  .add("Dir Lower");
        listHeadrs  .add("Dir Lower");
        listHeadrs  .add("Dir Upper");
        listHeadrs  .add("Dir Upper");
        listHeadrs  .add("Dir Upper");
        listHeadrs  .add("Chitral Lower");
        listHeadrs  .add("Chitral Lower");
        listHeadrs  .add("Chitral Lower");
        listHeadrs  .add("Bunner");
        listHeadrs  .add("Bunner");
        listHeadrs  .add("Bunner");
        listHeadrs  .add("Bunner");
        listHeadrs  .add("Bunner");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Swat");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Shangla");
        listHeadrs  .add("Bannu");
        listHeadrs  .add("Bannu");
        listHeadrs  .add("Bannu");
        listHeadrs  .add("Bannu");
        listHeadrs  .add("Bannu");
        listHeadrs  .add("D.I.Khan");
        listHeadrs  .add("D.I.Khan");
        listHeadrs  .add("D.I.Khan");
        listHeadrs  .add("D.I.Khan");
        listHeadrs  .add("D.I.Khan");
        listHeadrs  .add("North Waziristan");
        listHeadrs  .add("North Waziristan");
        listHeadrs  .add("North Waziristan");
        listHeadrs  .add("North Waziristan");
        listHeadrs  .add("LakkiMarwat");
        listHeadrs  .add("LakkiMarwat");
        listHeadrs  .add("LakkiMarwat");
        listHeadrs  .add("LakkiMarwat");
        listHeadrs  .add("Tank");
        listHeadrs  .add("Tank");
        listHeadrs  .add("Tank");
        listHeadrs  .add("Tank");
        listHeadrs  .add("Tank");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("swabi");
        listHeadrs  .add("Swabi");
        listHeadrs  .add("swabi");
        listHeadrs  .add("swabi");
        listHeadrs  .add("swabi");
        listHeadrs  .add("swabi");
        listHeadrs  .add("swabi");
        listHeadrs  .add("swabi");
        listHeadrs  .add("South Waziristan");
        listHeadrs  .add("South Waziristan");
        listHeadrs  .add("South Waziristan");
        listHeadrs  .add("Peshawar");
        listHeadrs  .add("Peshawar");
        listHeadrs  .add("Peshawar");
        listHeadrs  .add("Mohmand");
        listHeadrs  .add("Mohmand");
        listHeadrs  .add("Mohmand");
        listHeadrs  .add("Mohmand");
        listHeadrs  .add("Mohmand");
        listHeadrs  .add("Mohmand");
        listHeadrs  .add("khyber");
        listHeadrs  .add("khyber");
        listHeadrs  .add("khyber");
        listHeadrs  .add("khyber");
        listHeadrs  .add("LakkiMarwat");
        listHeadrs  .add("Bajaur");
        listHeadrs  .add("Bajaur");
        listHeadrs  .add("Bajaur");
        listHeadrs  .add("Bajaur");
        listHeadrs  .add("Bajaur");
        listHeadrs  .add("Bajaur");
        listHeadrs  .add("chitral upper");
        listHeadrs  .add("chitral upper");
        listHeadrs  .add("chitral upper");
        listHeadrs  .add("kohat");
        listHeadrs  .add("kohat");
        listHeadrs  .add("kohat");
        listHeadrs  .add("Orakzai");
        listHeadrs  .add("Orakzai");
        listHeadrs  .add("Orakzai");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("kurram");
        listHeadrs  .add("kurram");
        listHeadrs  .add("kurram");
        listHeadrs  .add("kurram");
        listHeadrs  .add("karak");
        listHeadrs  .add("karak");
        listHeadrs  .add("karak");
        listHeadrs  .add("karak");
        listHeadrs  .add("karak");
        listHeadrs  .add("karak");
        listHeadrs  .add("malakand");
        listHeadrs  .add("malakand");
        listHeadrs  .add("malakand");
        listHeadrs  .add("malakand");
        listHeadrs  .add("malakand");
        listHeadrs  .add("malakand");
        listHeadrs  .add("malakand");
        listHeadrs  .add("malakand");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");




        return listHeadrs;

    }


    public static ArrayList<String> gettehsil() {
        ArrayList<String> listHeadrs=new  ArrayList<String>();

        listHeadrs  .add("Mansehra");
        listHeadrs  .add("Mansehra");
        listHeadrs  .add("Balakot");
        listHeadrs  .add("Balakot");
        listHeadrs  .add("Oghi");
        listHeadrs  .add("Oghi");
        listHeadrs  .add("Battagram");
        listHeadrs  .add("Battagram");
        listHeadrs  .add("Alai");
        listHeadrs  .add("Hassan Zai");
        listHeadrs  .add("Pattan");
        listHeadrs  .add("Pattan");
        listHeadrs  .add("Pattan");
        listHeadrs  .add("Pattan");
        listHeadrs  .add("Dassu");
        listHeadrs  .add("Dassu");
        listHeadrs  .add("Dassu");
        listHeadrs  .add("Batera");
        listHeadrs  .add("Palas");
        listHeadrs  .add("Palas");
        listHeadrs  .add("Charsadda");
        listHeadrs  .add("Shabqadar");
        listHeadrs  .add("Tangi");
        listHeadrs  .add("Pabbi");
        listHeadrs  .add("Nowshera");
        listHeadrs  .add("Nowshera");
        listHeadrs  .add("Jehangira");
        listHeadrs  .add("Adenzai");
        listHeadrs  .add("Lal Qila");
        listHeadrs  .add("Timergara");
        listHeadrs  .add("Samar Bagh");
        listHeadrs  .add("Wari");
        listHeadrs  .add("Dir");
        listHeadrs  .add("Sheringal");
        listHeadrs  .add("Chitral");
        listHeadrs  .add("Chitral");
        listHeadrs  .add("Drosh");
        listHeadrs  .add("Daggar");
        listHeadrs  .add("Daggar");
        listHeadrs  .add("Gagra");
        listHeadrs  .add("Gagra");
        listHeadrs  .add("Mandanr");
        listHeadrs  .add("Babuzai");
        listHeadrs  .add("BariKot");
        listHeadrs  .add("Bahrain");
        listHeadrs  .add("Bahrain");
        listHeadrs  .add("Bahrain");
        listHeadrs  .add("Kwazakhela");
        listHeadrs  .add("Matta");
        listHeadrs  .add("Kabal");
        listHeadrs  .add("Kabal");
        listHeadrs  .add("Alpuri");
        listHeadrs  .add("Alpuri");
        listHeadrs  .add("Alpuri");
        listHeadrs  .add("Alpuri");
        listHeadrs  .add("Alpuri");
        listHeadrs  .add("Bisham");
        listHeadrs  .add("Bisham");
        listHeadrs  .add("Puran");
        listHeadrs  .add("Puran");
        listHeadrs  .add("Chakesar");
        listHeadrs  .add("Chakesar");
        listHeadrs  .add("Bannu");
        listHeadrs  .add("Domain");
        listHeadrs  .add("Domain");
        listHeadrs  .add("Domain");
        listHeadrs  .add("Baka Khel");
        listHeadrs  .add("D.I.Khan");
        listHeadrs  .add("D.I.Khan");
        listHeadrs  .add("Kulachi");
        listHeadrs  .add("Parao");
        listHeadrs  .add("PaharPur");
        listHeadrs  .add("Datta Khel");
        listHeadrs  .add("Miranshah");
        listHeadrs  .add("Mirali");
        listHeadrs  .add("Mirali");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("mardan");
        listHeadrs  .add("katlang");
        listHeadrs  .add("katlang");
        listHeadrs  .add("Rustam");
        listHeadrs  .add("Rustam");
        listHeadrs  .add("Rustam");
        listHeadrs  .add("Takht Bhai");
        listHeadrs  .add("Takht Bhai");
        listHeadrs  .add("Thakht Bhai");
        listHeadrs  .add("Topi");
        listHeadrs  .add("Topi");
        listHeadrs  .add("Lahor");
        listHeadrs  .add("lahor");
        listHeadrs  .add("Razzar");
        listHeadrs  .add("Razzar");
        listHeadrs  .add("Swabi");
        listHeadrs  .add("swabi");
        listHeadrs  .add("Ladha");
        listHeadrs  .add("Sarwakai");
        listHeadrs  .add("Wana");
        listHeadrs  .add("peshawar");
        listHeadrs  .add("peshawar");
        listHeadrs  .add("peshawar");
        listHeadrs  .add("Halimzai");
        listHeadrs  .add("Halimzai");
        listHeadrs  .add("Halimzai");
        listHeadrs  .add("ekkEkka Gund");
        listHeadrs  .add("Safi");
        listHeadrs  .add("Safi");
        listHeadrs  .add("Bara");
        listHeadrs  .add("bara");
        listHeadrs  .add("Jamrud");
        listHeadrs  .add("Landikotal");
        listHeadrs  .add("Sarai Naurang");
        listHeadrs  .add("khar");
        listHeadrs  .add("khar");
        listHeadrs  .add("Nawagai");
        listHeadrs  .add("Mamund");
        listHeadrs  .add("Mamund");
        listHeadrs  .add("Barang");
        listHeadrs  .add("Mastuj");
        listHeadrs  .add("Mastuj");
        listHeadrs  .add("Mastuj");
        listHeadrs  .add("kohat");
        listHeadrs  .add("kohat");
        listHeadrs  .add("lachi");
        listHeadrs  .add("upper Orakzai");
        listHeadrs  .add("upper Orakzai");
        listHeadrs  .add("Lower Orakzai");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Hangu");
        listHeadrs  .add("Tall");
        listHeadrs  .add("thall");
        listHeadrs  .add("uper kurram");
        listHeadrs  .add("uper kurram");
        listHeadrs  .add("uper kurram");
        listHeadrs  .add("central  kurram");
        listHeadrs  .add("karak");
        listHeadrs  .add("karak");
        listHeadrs  .add("Takht e Nasrati");
        listHeadrs  .add("Takht e Nasrati");
        listHeadrs  .add("Banda Daud Shah");
        listHeadrs  .add("Banda Daud Shah");
        listHeadrs  .add("Batkhela");
        listHeadrs  .add("Batkhela");
        listHeadrs  .add("Batkhela");
        listHeadrs  .add("bathela");
        listHeadrs  .add("Dargai");
        listHeadrs  .add("Dargai");
        listHeadrs  .add("Dargai");
        listHeadrs  .add("Dargai");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Abbottabad");
        listHeadrs  .add("Havelian");
        listHeadrs  .add("Havelian");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Haripur");
        listHeadrs  .add("Ghazi");
        listHeadrs  .add("Ghazi");
        listHeadrs  .add("Ghazi");
        listHeadrs  .add("Ghazi");
        listHeadrs  .add("khan pur");
        listHeadrs  .add("khan pur");





        return listHeadrs;

    }



    public static ArrayList<String> getname() {
        ArrayList<String> listHeadrs=new  ArrayList<String>();


        listHeadrs  .add("Regional Institute for Teacher Education");
        listHeadrs  .add("GPG College, Mansehra");
        listHeadrs  .add("GHS Balakot City");
        listHeadrs  .add("GD College Balakot");
        listHeadrs  .add("GD College for Boys, Oghi.");
        listHeadrs  .add("Govt English Medium Secondary School, Oghi");
        listHeadrs  .add("Newly Constructed Social Welfare Building.");
        listHeadrs  .add("GD College Battagram");
        listHeadrs  .add("Sports Ground, Alai");
        listHeadrs  .add("Sports Ground, Hassan Zai");
        listHeadrs  .add("GD College Pattan");
        listHeadrs  .add("GHSS, Pattan");
        listHeadrs  .add("GHS, Jijal");
        listHeadrs  .add("GHSS, Chakai");
        listHeadrs  .add("Govt Centennial Model High School and Adjacent Ground, Dassu.");
        listHeadrs  .add("Newly Constructed DHQ Hospital, Dassu");
        listHeadrs  .add("GHS Seo, Dassu");
        listHeadrs  .add("GHSS, Batera");
        listHeadrs  .add("GGHS, Palas");
        listHeadrs  .add("Wild life Building, Palas");
        listHeadrs  .add("GPG College Charsadda");
        listHeadrs  .add("GD College Shabqadar");
        listHeadrs  .add("GD College, Tangi");
        listHeadrs  .add("Jozai Camp");
        listHeadrs  .add("Government Technical College");
        listHeadrs  .add("Benazir Complex, Risalpur");
        listHeadrs  .add("GHS, Khairabad");
        listHeadrs  .add("University of Malakand Ground");
        listHeadrs  .add("Govt Degree College, Lal Qila");
        listHeadrs  .add("Govt Degree College Timergara");
        listHeadrs  .add("Govt Degree College, Samar Bagh");
        listHeadrs  .add("Govt Technical College Wari");
        listHeadrs  .add("Sports Stadium Dir");
        listHeadrs  .add("Shaheed Benazir Bhutoo University Ground");
        listHeadrs  .add("Polo Ground Chitral");
        listHeadrs  .add("Govt Centennial Model School Ground");
        listHeadrs  .add("Col Murad Stadium");
        listHeadrs  .add("Govt: Higher Secondary School  Jowar");
        listHeadrs  .add("Govt: Higher Secondary School Jawkhela");
        listHeadrs  .add("Govt Higher Secondary School Gagra");
        listHeadrs  .add("Govt Degree College Daggar,");
        listHeadrs  .add("Captain Waqas Shaheed Stadium, Mandanr");
        listHeadrs  .add("Govt: Jehanzeb College, Mingora");
        listHeadrs  .add("Govt: Higher Secondary School, Barikot");
        listHeadrs  .add("Govt: High and Higher Secondary School, Kalam");
        listHeadrs  .add("Govt High School Bahrain");
        listHeadrs  .add("Govt: higher Secondary School, Madyan");
        listHeadrs  .add("Govt Degree College Madyan");
        listHeadrs  .add("Govt: Post Graduate College Matta");
        listHeadrs  .add("Govt: Higher Secondary School, Kabal");
        listHeadrs  .add("Govt: Dr. Khan Shaheed Degree College, Kabal");
        listHeadrs  .add("Govt: Degree College, Alpuri");
        listHeadrs  .add("Govt: High School, Derai");
        listHeadrs  .add("Govt: Higher Secondary School and Primary school,  Shahpur");
        listHeadrs  .add("Govt: High School, Kuz Kana");
        listHeadrs  .add("Govt: High School, Karora");
        listHeadrs  .add("Govt Higher Secondary School, Botyal");
        listHeadrs  .add("KDP Ground, Botyal");
        listHeadrs  .add("Govt Degree College Puran");
        listHeadrs  .add("Govt High School, Puran");
        listHeadrs  .add("Govt: High School, Chakesar");
        listHeadrs  .add("Govt Degree College,  Chakesar");
        listHeadrs  .add("Bannu Sugar Mill");
        listHeadrs  .add("Kashu Bridge");
        listHeadrs  .add("Govt Degree College. Landi Jalandar");
        listHeadrs  .add("Govt: Degree College Spina Tangi");
        listHeadrs  .add("TDP Camp Baka Khel");
        listHeadrs  .add("Sports Complex D.I.Khan");
        listHeadrs  .add("Gomal Medical College Ground:");
        listHeadrs  .add("Sports Stadium Kulachi");
        listHeadrs  .add("Sports Stadium Parao");
        listHeadrs  .add("Govt: Degree College, Paharpur");
        listHeadrs  .add("Datta Khel Camp Near Newly Constructed Tehsil Building");
        listHeadrs  .add("Govt post graduate college Miranshah");
        listHeadrs  .add("Govt Degree College");
        listHeadrs  .add("Govt  Elementary Teacher Traning  college");
        listHeadrs  .add("govt  High Centennial Model LakkiMarwat City");
        listHeadrs  .add("Govt Post Graduate College Lakki Marwat");
        listHeadrs  .add("Govt Degree College Landiwah");
        listHeadrs  .add("Govt High Secondary School Landiwah");
        listHeadrs  .add("Govt Higher Secondary school Gomal Bazar");
        listHeadrs  .add("Govt Degree College Tank");
        listHeadrs  .add("Muhajr Camp");
        listHeadrs  .add("Jehaz Ground Tank City");
        listHeadrs  .add("Govt Degree College Amakhel Tank");
        listHeadrs  .add("Govt Post Graduate College Mardan");
        listHeadrs  .add("Military Diary Farm Mardan");
        listHeadrs  .add("Govt Degree College, Toru");
        listHeadrs  .add("Govt Degree Coolege for Girls");
        listHeadrs  .add("Govt Degree College Katlang");
        listHeadrs  .add("Sports Complex, Rustam");
        listHeadrs  .add("Govt Girls Degree College, Rustam");
        listHeadrs  .add("Govt Degree College Khair Abad,");
        listHeadrs  .add("Govt Degree College, Takhtbhai");
        listHeadrs  .add("Govt Degree College, Lund Khwar");
        listHeadrs  .add("Govt Higher Secondary School, Hathian");
        listHeadrs  .add("Govt High School, Topi");
        listHeadrs  .add("Govt Girls Degree College Topi");
        listHeadrs  .add("University of Swabi");
        listHeadrs  .add("Govt Degree College, Lahor");
        listHeadrs  .add("Govt Degree College Yar Hussain");
        listHeadrs  .add("Govt. Degree College, Shewa");
        listHeadrs  .add("Govt Polytechnic Institute Shahmansoor");
        listHeadrs  .add("Baja Sports Complex");
        listHeadrs  .add("Govt Degree College, Ladha");
        listHeadrs  .add("Moula Khan Surai Hospital, Sarwakai");
        listHeadrs  .add("Wana Cricket Stadium & Adjacent Area");
        listHeadrs  .add("Govt Degree College Naguman");
        listHeadrs  .add("Zamung Kor");
        listHeadrs  .add("Govt Girls Degree College, Chagharmatti");
        listHeadrs  .add("Govt Higher Secondary School, Ghalanai");
        listHeadrs  .add("Sports Complex Ghalanai");
        listHeadrs  .add("Govt Degree College Chanda");
        listHeadrs  .add("Govt: Degree College, Ekka Gund");
        listHeadrs  .add("Govt Degree College, Lakaro");
        listHeadrs  .add("Tehsil Headquarter Hospital, Mamad Gut");
        listHeadrs  .add("Govt Degree College, Kohi Sher Haider");
        listHeadrs  .add("Govt Girls Higher Secondary School, Kalanda, Aka Khel");
        listHeadrs  .add("Jamrud Cricket Ground");
        listHeadrs  .add("Govt Degree College, Landi Kotal & Adjucent Rehman Baba Tomb Ground");
        listHeadrs  .add("Govt: Degree College, Sarai Naurang");
        listHeadrs  .add("Sports Complex, Khar");
        listHeadrs  .add("Govt: Degree College, Khar");
        listHeadrs  .add("Govt Degree College, Nawagai");
        listHeadrs  .add("Govt Degree College Bar khalozai");
        listHeadrs  .add("Govt: high School, Bar Kalozai");
        listHeadrs  .add("Govt High School, Ghani Adai");
        listHeadrs  .add("Govt Girls Degree College, Booni");
        listHeadrs  .add("Govt: Boys Degree College Booni");
        listHeadrs  .add("Ghali Ground, Mastuj");
        listHeadrs  .add("Qila Ground, Kohat");
        listHeadrs  .add("Govt Post Graduate College, Kohat");
        listHeadrs  .add("Govt Girls Degree College, Lachi");
        listHeadrs  .add("Govt Degree College Ghiljo");
        listHeadrs  .add("Sports Stadium Ghiljo");
        listHeadrs  .add("Kalaya Sports Ground");
        listHeadrs  .add("Sports Complex, Hangu");
        listHeadrs  .add("Govt Degree College, Hangu");
        listHeadrs  .add("Govt Girls Degree College & Adjacent Railway Ground, Hangu");
        listHeadrs  .add("Khwaja Khizar (Forest Land)");
        listHeadrs  .add("Govt Higher Secondary School, Doaba");
        listHeadrs  .add("Govt Degree College, Thall");
        listHeadrs  .add("Govt Degree College, Parachinar");
        listHeadrs  .add("Cricket Ground, Sadda");
        listHeadrs  .add("Govt High School, Alizai");
        listHeadrs  .add("Govt High School, Dogar");
        listHeadrs  .add("Govt Girls Centennial Model Higher Secondary School, Karak");
        listHeadrs  .add("Govt Post Graduate College, Karak");
        listHeadrs  .add("Takht- e- Naarati Sports Complex");
        listHeadrs  .add("Govt Degree College, Takht-e-Nasarati");
        listHeadrs  .add("Govt Degree College, Banda Daud Shah");
        listHeadrs  .add("Govt Girls Degree College Banda Daud Shah");
        listHeadrs  .add("Govt: Degree College, Totakan");
        listHeadrs  .add("Govt Higher Secondary School, Khar");
        listHeadrs  .add("Zafar Park Batkhela");
        listHeadrs  .add("Govt: Degree College, Thana");
        listHeadrs  .add("Govt: Post Graduate College, Dargai");
        listHeadrs  .add("Govt: Higher School Heroshah");
        listHeadrs  .add("Govt: Degree College, Badraga");
        listHeadrs  .add("Govt: Higher Secondary School, Sakhakot");
        listHeadrs  .add("Govt: High School No3 Abbottabad");
        listHeadrs  .add("Govt: Post Graduate College No 1 Abbottabad");
        listHeadrs  .add("Cricket Stadium Nawan shehr, Abbottabad");
        listHeadrs  .add("Cricket Ground Township Nawan shehr");
        listHeadrs  .add("Govt: Post Graduate College, Mandian");
        listHeadrs  .add("Govt Degree College, Havelian");
        listHeadrs  .add("Abbottabad University of Science & Technology, Havelian");
        listHeadrs  .add("Pak China Fertilizer Colony, Haripur");
        listHeadrs  .add("Afghan Refugee Camp Basso Road");
        listHeadrs  .add("Govt High School, Panian");
        listHeadrs  .add("Padhana Camp Site");
        listHeadrs  .add("WAPDA Ground  (Infront of AC Office)");
        listHeadrs  .add("Govt Degree College,  Ghazi");
        listHeadrs  .add("Sports Stadium Hussan Pur");
        listHeadrs  .add("Govt High School, Ghazi");
        listHeadrs  .add("Govt High School, Khan Pur");
        listHeadrs  .add("Govt: Degree College Khanpur");


        return listHeadrs;

    }


    public static ArrayList<String> getlocaiton() {
        ArrayList<String> listHeadrs=new  ArrayList<String>();


        listHeadrs  .add("Main Shahrah e Resham, Near Ghazi Kot Town Ship, Mansehra.");
        listHeadrs  .add("Labor Kot College Doraha, Mansehra");
        listHeadrs  .add("Mansehra Naran Road");
        listHeadrs  .add("Hassa, Mansehra Naran Road");
        listHeadrs  .add("College Road Oghi");
        listHeadrs  .add("Main Battagram Road.");
        listHeadrs  .add("Shahrah e Resham, Chapargam Battagram");
        listHeadrs  .add("College Road, Shahrah e Resham, Battagram");
        listHeadrs  .add("Kasai Bana, Kwand Road Alai");
        listHeadrs  .add("Thakot Darband Road");
        listHeadrs  .add("WAPDA Colony Road, Pattan");
        listHeadrs  .add("Tehsil Road, Main Bazar Pattan");
        listHeadrs  .add("Karakorum Highway, Jijal");
        listHeadrs  .add("Karakorum Highway, Chakai");
        listHeadrs  .add("Karakorum Highway Road, Dassu City");
        listHeadrs  .add("AC Colony Link Road, Karakorum Highway Dassu");
        listHeadrs  .add("Dassu Seo Road, Seo");
        listHeadrs  .add("Batera Bisham Road, Batera");
        listHeadrs  .add("Ziarat Road, Palas");
        listHeadrs  .add("Ziarat Road, Palas");
        listHeadrs  .add("Prang Road Charsadda");
        listHeadrs  .add("Battagram Road, Shabqadar");
        listHeadrs  .add("College Road Tangi");
        listHeadrs  .add("Chirat Pabbi Road, Jalozai");
        listHeadrs  .add("Nowshera  Mardan Road");
        listHeadrs  .add("Bara Banda link Road Risalpur, Nowshera.");
        listHeadrs  .add("Nizam Pur Road Khairabad");
        listHeadrs  .add("Chakdara Ramda/University Road");
        listHeadrs  .add("College Road, Maidan");
        listHeadrs  .add("Maidan Road, Haji Abad, Timergara Road");
        listHeadrs  .add("Samarbagh Timergara Road");
        listHeadrs  .add("Main Wari Bazar, Dir Chitral Road");
        listHeadrs  .add("Dir Chitral Road, Main Dir Bazar");
        listHeadrs  .add("Dir Kumrat Road");
        listHeadrs  .add("Peshawar Chitral Road");
        listHeadrs  .add("Shahi Masjid Road, Chitral");
        listHeadrs  .add("Chitral Peshawar Road, Drosh");
        listHeadrs  .add("Main Barikot Daggar Road");
        listHeadrs  .add("Daggar Pir Baba Road");
        listHeadrs  .add("Gagra Tehsil, Road");
        listHeadrs  .add("Dewana Baba Road");
        listHeadrs  .add("Chamla Road, Mandanr");
        listHeadrs  .add("Saidu Sharif Road, Mingora");
        listHeadrs  .add("Peshawar Mingora Road, Barikot");
        listHeadrs  .add("Tehsil Road, Kalam");
        listHeadrs  .add("Tehsil Road, Bahrain");
        listHeadrs  .add("School Road Madyan");
        listHeadrs  .add("Madyan Mingora Road");
        listHeadrs  .add("Matta Mingora road");
        listHeadrs  .add("Police Line Kabal");
        listHeadrs  .add("Kabal Mingora Road");
        listHeadrs  .add("College Road, Alpuri");
        listHeadrs  .add("Alpuri Bisham Road, Derai");
        listHeadrs  .add("Shahpur Karora Road, Shahpur");
        listHeadrs  .add("Shahpur Karora Road, Kuz Kana");
        listHeadrs  .add("Alpuri Bisham Road, Karora");
        listHeadrs  .add("Kurakuram highway, Bisham");
        listHeadrs  .add("Kurakuram highway, Bisham");
        listHeadrs  .add("Yakh Tangi Puran road");
        listHeadrs  .add("Yakh Tangi Puran road");
        listHeadrs  .add("Karora Chakesar, road");
        listHeadrs  .add("Karora Chakesar, road");
        listHeadrs  .add("Bannu-D.I.Khan Road");
        listHeadrs  .add("Indus High Way Bannu Link Road");
        listHeadrs  .add("Peshawar D.I.Khan Road");
        listHeadrs  .add("Kohat Bannu Road");
        listHeadrs  .add("Miranshah Road Baka Khel");
        listHeadrs  .add("Bannu Road D.I.Khan");
        listHeadrs  .add("Drabin Road D.I.Khan");
        listHeadrs  .add("Kachri near Kulachi D.I.Khan Road");
        listHeadrs  .add("Indus High Way Parao");
        listHeadrs  .add("Pahar Pur D.I.Khan Road");
        listHeadrs  .add("Miran Shah Datta khel Road");
        listHeadrs  .add("Mivali Miran Shah Road");
        listHeadrs  .add("Miran Shah Road Mirali");
        listHeadrs  .add("Miran Shah Road Mirali");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");
        listHeadrs  .add("?");


        return listHeadrs;

    }


    public static ArrayList<String> getGPS() {
        ArrayList<String> listHeadrs=new  ArrayList<String>();

        listHeadrs  .add("34.30495,73.21599");
        listHeadrs  .add("34.36603,73.21424");
        listHeadrs  .add("34.54826,73.35104");
        listHeadrs  .add("34.51388,73.35097");
        listHeadrs  .add("34.50815,73.00544");
        listHeadrs  .add("34.42399,72.96968");
        listHeadrs  .add("34.666039,73.048073");
        listHeadrs  .add("34.651672,73.055207");
        listHeadrs  .add("34.837681,73.056076");
        listHeadrs  .add("34.436944,72.822222");
        listHeadrs  .add("35.11367,73.01252");
        listHeadrs  .add("35.10804,73.00478");
        listHeadrs  .add("35.04061,72.92371");
        listHeadrs  .add("34.99747,72.90739");
        listHeadrs  .add("35.2744,73.22289");
        listHeadrs  .add("35.2764,73.22533");
        listHeadrs  .add("35.30587,73.18956");
        listHeadrs  .add("34.9463,72.88481");
        listHeadrs  .add("35.10331,72.99794");
        listHeadrs  .add("35.10282,72.99835");
        listHeadrs  .add("34.143814,71.739163");
        listHeadrs  .add("34.218736,71.584472");
        listHeadrs  .add("34.320172,71.64843");
        listHeadrs  .add("33.930979,71.810834");
        listHeadrs  .add("34.034454,71.99973");
        listHeadrs  .add("34.059526,72.012031");
        listHeadrs  .add("33.895717,72.228595");
        listHeadrs  .add("34.665893,72.061232");
        listHeadrs  .add("34.957314,71.818308");
        listHeadrs  .add("34.845316,71.828839");
        listHeadrs  .add("34.918333,71.695833");
        listHeadrs  .add("34.992222,72.0375");
        listHeadrs  .add("35.19984,71.87475");
        listHeadrs  .add("35.27588,72.006006");
        listHeadrs  .add("35.84707,71.7843");
        listHeadrs  .add("35.854625,71.789457");
        listHeadrs  .add("35.555088,71.794758");
        listHeadrs  .add("0,72.30465");
        listHeadrs  .add("34.582129,72.4479");
        listHeadrs  .add("34.474336,72.540086");
        listHeadrs  .add("34.478074,72.486329");
        listHeadrs  .add("34.40422,72.498314");
        listHeadrs  .add("34.75616,72.35787");
        listHeadrs  .add("34.67639,72.21906");
        listHeadrs  .add("35.479788,72.584808");
        listHeadrs  .add("35.20653,72.5456");
        listHeadrs  .add("35.140132,72.533902");
        listHeadrs  .add("35.102557,72.50788");
        listHeadrs  .add("34.929819,72.412544");
        listHeadrs  .add("34.794677,72.293125");
        listHeadrs  .add("34.791972,72.289067");
        listHeadrs  .add("34.9242,72.63383");
        listHeadrs  .add("34.87406,72.71543");
        listHeadrs  .add("34.94996,72.74886");
        listHeadrs  .add("34.918282,72.756");
        listHeadrs  .add("34.888894,72.766788");
        listHeadrs  .add("34.913306,72.868544");
        listHeadrs  .add("34.916213,72.871596");
        listHeadrs  .add("34.755659,72.67724");
        listHeadrs  .add("34.802328,72.663221");
        listHeadrs  .add("34.78341,72.767186");
        listHeadrs  .add("34.790288,72.772111");
        listHeadrs  .add("32.84569,70.76472");
        listHeadrs  .add("32.9784,70.8336");
        listHeadrs  .add("32.88116,70.91374");
        listHeadrs  .add("33.05772,70.80053");
        listHeadrs  .add("32.97487,70.47219");
        listHeadrs  .add("31.87098,70.89312");
        listHeadrs  .add("31.814114,70.821433");
        listHeadrs  .add("31.92274,70.46581");
        listHeadrs  .add("31.56445,70.76735");
        listHeadrs  .add("32.106317,70.977296");
        listHeadrs  .add("32.907248,69.760346");
        listHeadrs  .add("33.001349,70.075044");
        listHeadrs  .add("32.951448,70.322629");
        listHeadrs  .add("32.952247,70.321775");
        listHeadrs  .add("32.6105371,70.9076866");
        listHeadrs  .add("32.61372,70.89413");
        listHeadrs  .add("32.73333,70.98836");
        listHeadrs  .add("32.74841,70.97102");
        listHeadrs  .add("32.1224133,70.154939");
        listHeadrs  .add("32.21194,70.39487");
        listHeadrs  .add("32.14051,70.2223");
        listHeadrs  .add("32.20277,70.39624");
        listHeadrs  .add("32.37856,70.51774");
        listHeadrs  .add("34.19125,72.03606");
        listHeadrs  .add("34.19535,71.98712");
        listHeadrs  .add("34.11997,72.09988");
        listHeadrs  .add("34.301848,72.093871");
        listHeadrs  .add("34.37025,72.07968");
        listHeadrs  .add("34.33168,72.30352");
        listHeadrs  .add("34.32953,72.2513");
        listHeadrs  .add("34.286009,72.213121");
        listHeadrs  .add("34.27304,71.92964");
        listHeadrs  .add("34.3903,71.96891");
        listHeadrs  .add("34.38228,71.92217");
        listHeadrs  .add("34.07449,72.62218");
        listHeadrs  .add("34.06571,72.523241");
        listHeadrs  .add("34.056777,72.409305");
        listHeadrs  .add("34.021343,72.348042");
        listHeadrs  .add("34.125028,72.29425");
        listHeadrs  .add("34.246309,72.33468");
        listHeadrs  .add("34.076081,72.464137");
        listHeadrs  .add("34.127054,72.520106");
        listHeadrs  .add("32.564711,69.830999");
        listHeadrs  .add("32.286083,69.923028");
        listHeadrs  .add("32.308944,69.571285");
        listHeadrs  .add("34.12216,71.60032");
        listHeadrs  .add("34.07386,71.59314");
        listHeadrs  .add("34.12288,71.51359");
        listHeadrs  .add("34.32006,71.41226");
        listHeadrs  .add("34.32299,71.40303");
        listHeadrs  .add("34.33551,71.3923");
        listHeadrs  .add("34.24271,71.49342");
        listHeadrs  .add("34.55324,71.26132");
        listHeadrs  .add("34.6259,71.262285");
        listHeadrs  .add("33.90387,71.353279");
        listHeadrs  .add("33.904549,71.460577");
        listHeadrs  .add("33.999775,71.382954");
        listHeadrs  .add("34.103898,71.159552");
        listHeadrs  .add("32.8306,70.78057");
        listHeadrs  .add("34.72582,71.49406");
        listHeadrs  .add("34.75505,71.54561");
        listHeadrs  .add("34.685134,71.338884");
        listHeadrs  .add("34.790209,71.404696");
        listHeadrs  .add("34.791698,71.406713");
        listHeadrs  .add("34.701125,71.562232");
        listHeadrs  .add("36.261981,72.225769");
        listHeadrs  .add("36.251797,72.202404");
        listHeadrs  .add("36.279158,72.249356");
        listHeadrs  .add("33.5906,71.43551");
        listHeadrs  .add("33.573763,71.466677");
        listHeadrs  .add("33.359972,71.317565");
        listHeadrs  .add("33.641032,70.83869");
        listHeadrs  .add("33.64885,70.84106");
        listHeadrs  .add("33.749614,70.957149");
        listHeadrs  .add("33.52098,71.05145");
        listHeadrs  .add("33.516947,71.046537");
        listHeadrs  .add("33.52506,71.06615");
        listHeadrs  .add("33.57641,71.20053");
        listHeadrs  .add("33.42242,70.72696");
        listHeadrs  .add("33.37803,70.5809");
        listHeadrs  .add("33.88513,70.11461");
        listHeadrs  .add("33.702537,70.33946");
        listHeadrs  .add("33.536391,70.348766");
        listHeadrs  .add("33.775613,70.514415");
        listHeadrs  .add("33.10887,71.07631");
        listHeadrs  .add("33.10362,71.06506");
        listHeadrs  .add("33.011024,71.085924");
        listHeadrs  .add("33.00727,71.07247");
        listHeadrs  .add("33.279968,71.157462");
        listHeadrs  .add("33.282277,71.167187");
        listHeadrs  .add("34.6189,71.81835");
        listHeadrs  .add("34.608774,71.93581");
        listHeadrs  .add("34.6214,71.97983");
        listHeadrs  .add("34.6309,72.06897");
        listHeadrs  .add("34.508628,71.909395");
        listHeadrs  .add("34.42809,71.822716");
        listHeadrs  .add("34.395063,71.843596");
        listHeadrs  .add("34.458935,71.905274");
        listHeadrs  .add("34.14541,73.21273");
        listHeadrs  .add("34.14756,73.22023");
        listHeadrs  .add("34.1542,73.26122");
        listHeadrs  .add("34.18423,73.27865");
        listHeadrs  .add("34.19702,73.22921");
        listHeadrs  .add("34.055114,73.1658");
        listHeadrs  .add("34.068452,73.150127");
        listHeadrs  .add("33.9706,72.89409");
        listHeadrs  .add("34.03473,72.84542");
        listHeadrs  .add("33.972836,72.854871");
        listHeadrs  .add("34.04154,72.91377");
        listHeadrs  .add("34.02125,72.66261");
        listHeadrs  .add("33.99984,72.66376");
        listHeadrs  .add("33.97765,72.59516");
        listHeadrs  .add("34.01872,72.65887");
        listHeadrs  .add("33.80349,72.91442");
        listHeadrs  .add("33.790808,72.91234");



        return listHeadrs;

    }







}
